export const words = {
  'oli': {
    'olli': {'common': ['collier', 'collimateur', 'colline', 'collision', 'follicule', 'pollinisateur', 'ramollir', 'solliciter']},
    'olly': {'proper': ['Molly']},
    'oli': {
      'common': [
        'abolir', 
        'acoolisme',
        'brocoli',
        'bucolique',
        'catholique',
        'colibri',
        'colimaçon',
        'colis', 
        'colisée',
        'cosmopolite',
        'démolir',
        'diabolique',
        'écolier',
        'embolie',
        'éolienne',
        'folie',
        'geôlier', 
        'gondolier', 
        'joli', 
        'mélancolie', 
        'olive', 
        'poli', 
        'politique',
        'scoliose',
        'solide', 
        'soliloque', 
        'solitude', 
        'symbolique',
        'torticolis',
        'volière'
      ],
      'proper': ['Bolivie', 'Molière', 'Mongolie'],
      'alt' : ['ôli']},
    'oly': {'common': ['polymère', 'polyvalent']}
  },
  'eli': {
    'elli': {
      'common': ['belliqueux', 'cellier', 'ellipse', 'embellir', 'intelligible', 'intelligence', 'pellicule', 'rébellion', 'satellite'],
      'proper': ['Montpellier']},
    'elly': {
      'proper': ['Kelly', 'Nelly']
    },
    'éli': {
      'common': [
        'améliorer', 
        'angélique', 
        'bélier', 
        'célibataire', 
        'délibération', 
        'délicat', 
        'délice', 
        'délier', 
        'délire',
        'délit',
        'délivrer',
        'éliminer',
        'élire',
        'élite',
        'élixir',
        'félicitation',
        'fidélité',
        'hélice',
        'héliocentrique',
        'hélium',
        'obélisque',
        'pélican'],
      'proper': ['Élie', 'Élise', 'Montbéliard'],
      'alt': ['eli', 'Éli']
    },
    'ely': {
      'proper': ['Élysée'],
      'alt': ['Ély', 'ely']
    }
  },
  'ali': {
    'alli': {
      'common': [
        'alliage',
        'alliance',
        'alligator',
        'allitération',
        'calligraphie',
        'callipyge',
        'corallien',
        'cristallin',
        'métallique',
        'palliatif',
        'pallier',
        'phallique',
        'ralliement',
        'thallium',
      ]
    },
    'ally': { 'common': ['rallye']},
    'ali' : {
      'common': [
        'alien',
        'animalier',
        'anomalie',
        'balise',
        'balistique',
        'baliverne',
        'banaliser',
        'brutalité',
        'buraliste',
        'calibrer',
        'calice',
        'calife',
        'califourchon',
        'canaliser',
        'capitalisme',
        'causalité',
        'cavalière',
        'centraliser',
        'chevalier',
        'chrysalide',
        'coalition',
        'commercialiser',
        'confidentialité',
        'contextualiser',
        'convivialité',
        'dualité',
        'délocalisation',
        'dévaliser',
        'égalité',
        'escalier',
        'espalier',
        'fatalité',
        'finaliste',
        'fiscalité',
        'focaliser',
        'formalité',
        'frontalier',
        'galion',
        'galipette',
        'généralité',
        'hospitalier',
        'idéaliste',
        'initialiser',
        'journalier',
        'nationalité'

      ],
      'proper': [ 'Alice', 'Australie', 'Californie', 'Galice'],
      'alt': ['Ali']
    },
    'aly': {
      'common': ['analyse', 'apocalypse', 'catalyseur', 'dialyse', 'eucalyptus', 'paralympique', 'paralyser'],
      'proper': ['Calypso'],
      'alt': ['Aly']
    }
  },
  'ole': {
    'olle': {
      'common': ['colle', 'collection', 'collège', 'collet', 'folle', 'follet', 'girolle', 'grolle', 'molle', 'mollet', 'roller', 'tollé', 'troller', 'volley'],
      'alt': ['ollè', 'ollé']
    },
    'aulle': {
      'common': [],
      'proper': ['Charles de Gaulle']
    },
    'ole': {
      'common': [
        'accoler',
        'acropole',
        'adolescence',
        'affoler',
        'agricole',
        'alvéole',
        'auréole',
        'babiole',
        'bagnole',
        'batifoler',
        'bolet',
        'boussole',
        'bricoler',
        'bénévole',
        'cabriolet',
        'cajole',
        'cambrioler',
        'camisole',
        'caracole',
        'casserole',
        'contrôle',
        'console',
        'coupole',
        'créole',
        'dégringoler',
        'drôle',
        'école',
        'enjôleur',
        'farandole',
        'faribole',
        'fignoler',
        'fiole',
        'flageolet',
        'frivole',
        'frôler',
        'gondole',
        'hyperbole',
        'idole',
        'immoler',
        'insolence',
        'isoler',
        'luciole',
        'métropole',
        'molette',
        'obole',
        'pactole',
        'pôle',
        'protocole',
        'pétrole',
        'racoleur',
        'raffoler',
        'rafistoler',
        'rigoler',
        'rissoler',
        'rocambolesque',
        'rôle',
        'rougeole',
        'soleil',
        'solennel',
        'somnolence',
        'tôle',
        'torgnole',
        'triolet',
        'variole',
        'vérole',
        'violence',
        'violet',
        'voler',
        'volet',
        'yole'
      ],
      'alt': ['ôle']
    },
    'aule': {
      'common': ['épaule', 'gaule', 'miauler', 'piaule', 'saule', 'taule'],
      'proper': ['La Gaule']
    }
  }
}